import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsString, IsOptional, IsBoolean, IsArray, IsNumber, MinLength, IsNotEmpty, ValidateNested, Min, Max, ArrayMinSize } from 'class-validator';
import { Type } from 'class-transformer';

export class StationPricingDto {
  @ApiProperty({
    description: 'Number of players for this pricing',
    example: 1,
    minimum: 1,
  })
  @IsNumber()
  @IsNotEmpty()
  @Min(1)
  playerCount: number;

  @ApiProperty({
    description: 'Price per hour for this number of players',
    example: 250000,
    minimum: 0,
  })
  @IsNumber()
  @IsNotEmpty()
  @Min(0)
  price: number;

  // Note: Fields like id, stationId, createdAt, updatedAt should NOT be sent in requests
  // They are auto-generated by the database. The service will filter out these extra fields.
}

export class CreateStationDto {
  @ApiProperty({
    description: 'Organization ID',
    example: 1,
  })
  @IsNumber()
  @IsNotEmpty()
  organizationId: number;

  @ApiProperty({
    description: 'Station title',
    example: 'Station 1 - PlayStation 5',
    minLength: 3,
  })
  @IsString()
  @MinLength(3)
  @IsNotEmpty()
  title: string;

  @ApiProperty({
    description: 'Console ID',
    example: 1,
  })
  @IsNumber()
  @IsNotEmpty()
  consoleId: number;

  @ApiProperty({
    description: 'Station capacity (maximum number of people)',
    example: 6,
    minimum: 1,
  })
  @IsNumber()
  @IsNotEmpty()
  @Min(1)
  capacity: number;

  @ApiProperty({
    description: 'Pricing array - must have exactly one pricing per player count from 1 to capacity',
    example: [
      { playerCount: 1, price: 250000 },
      { playerCount: 2, price: 350000 },
      { playerCount: 3, price: 400000 },
      { playerCount: 4, price: 450000 },
      { playerCount: 5, price: 500000 },
      { playerCount: 6, price: 550000 },
    ],
    type: [StationPricingDto],
  })
  @IsArray()
  @ArrayMinSize(1)
  @ValidateNested({ each: true })
  @Type(() => StationPricingDto)
  pricings: StationPricingDto[];

  @ApiPropertyOptional({
    description: 'Station status (in use or not)',
    example: false,
    default: false,
  })
  @IsOptional()
  @IsBoolean()
  status?: boolean;

  @ApiPropertyOptional({
    description: 'Is station active',
    example: true,
    default: true,
  })
  @IsOptional()
  @IsBoolean()
  isActive?: boolean;

  @ApiPropertyOptional({
    description: 'Is station accepted by admin',
    example: false,
    default: false,
  })
  @IsOptional()
  @IsBoolean()
  isAccepted?: boolean;

  @ApiPropertyOptional({
    description: 'Game IDs for this station',
    example: [1, 2, 3],
    type: [Number],
  })
  @IsOptional()
  @IsArray()
  @IsNumber({}, { each: true })
  gameIds?: number[];
}

export class UpdateStationDto {
  @ApiPropertyOptional({
    description: 'Organization ID',
    example: 1,
  })
  @IsOptional()
  @IsNumber()
  organizationId?: number;

  @ApiPropertyOptional({
    description: 'Station title',
    example: 'Station 1 - PlayStation 5',
    minLength: 3,
  })
  @IsOptional()
  @IsString()
  @MinLength(3)
  title?: string;

  @ApiPropertyOptional({
    description: 'Console ID',
    example: 1,
  })
  @IsOptional()
  @IsNumber()
  consoleId?: number;

  @ApiPropertyOptional({
    description: 'Station capacity (maximum number of people)',
    example: 6,
    minimum: 1,
  })
  @IsOptional()
  @IsNumber()
  @Min(1)
  capacity?: number;

  @ApiPropertyOptional({
    description: 'Pricing array - must have exactly one pricing per player count from 1 to capacity',
    example: [
      { playerCount: 1, price: 250000 },
      { playerCount: 2, price: 350000 },
    ],
    type: [StationPricingDto],
  })
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => StationPricingDto)
  pricings?: StationPricingDto[];

  @ApiPropertyOptional({
    description: 'Station status (in use or not)',
    example: true,
  })
  @IsOptional()
  @IsBoolean()
  status?: boolean;

  @ApiPropertyOptional({
    description: 'Is station active',
    example: true,
  })
  @IsOptional()
  @IsBoolean()
  isActive?: boolean;

  @ApiPropertyOptional({
    description: 'Is station accepted by admin',
    example: true,
  })
  @IsOptional()
  @IsBoolean()
  isAccepted?: boolean;

  @ApiPropertyOptional({
    description: 'Game IDs for this station',
    example: [1, 2, 3, 4],
    type: [Number],
  })
  @IsOptional()
  @IsArray()
  @IsNumber({}, { each: true })
  gameIds?: number[];
}

export class StationPricingResponseDto {
  @ApiProperty({
    description: 'Pricing ID',
    example: 1,
  })
  id: number;

  @ApiProperty({
    description: 'Number of players',
    example: 1,
  })
  playerCount: number;

  @ApiProperty({
    description: 'Price per hour',
    example: 250000,
  })
  price: number;

  @ApiProperty({
    description: 'Creation timestamp',
    example: '2024-01-01T00:00:00.000Z',
  })
  createdAt: Date;

  @ApiProperty({
    description: 'Last update timestamp',
    example: '2024-01-01T00:00:00.000Z',
  })
  updatedAt: Date;
}

export class StationResponseDto {
  @ApiProperty({
    description: 'Station ID',
    example: 1,
  })
  id: number;

  @ApiProperty({
    description: 'Organization ID',
    example: 1,
  })
  organizationId: number;

  @ApiProperty({
    description: 'Station title',
    example: 'Station 1 - PlayStation 5',
  })
  title: string;

  @ApiProperty({
    description: 'Console ID',
    example: 1,
  })
  consoleId: number;

  @ApiProperty({
    description: 'Station capacity',
    example: 6,
  })
  capacity: number;

  @ApiProperty({
    description: 'Station status',
    example: false,
  })
  status: boolean;

  @ApiProperty({
    description: 'Is station active',
    example: true,
  })
  isActive: boolean;

  @ApiProperty({
    description: 'Is station accepted',
    example: false,
  })
  isAccepted: boolean;

  @ApiProperty({
    description: 'Pricing array',
    type: [StationPricingResponseDto],
  })
  pricings: StationPricingResponseDto[];

  @ApiProperty({
    description: 'Creation timestamp',
    example: '2024-01-01T00:00:00.000Z',
  })
  createdAt: Date;

  @ApiProperty({
    description: 'Last update timestamp',
    example: '2024-01-01T00:00:00.000Z',
  })
  updatedAt: Date;
}

export class SearchStationsDto {
  @ApiPropertyOptional({
    description: 'Number of players',
    example: 2,
    minimum: 1,
  })
  @IsOptional()
  @IsNumber()
  @Min(1)
  @Type(() => Number)
  playerCount?: number;

  @ApiPropertyOptional({
    description: 'Console ID',
    example: 1,
  })
  @IsOptional()
  @IsNumber()
  @Type(() => Number)
  consoleId?: number;

  @ApiPropertyOptional({
    description: 'Game ID',
    example: 1,
  })
  @IsOptional()
  @IsNumber()
  @Type(() => Number)
  gameId?: number;

  @ApiPropertyOptional({
    description: 'Organization ID',
    example: 1,
  })
  @IsOptional()
  @IsNumber()
  @Type(() => Number)
  organizationId?: number;

  @ApiPropertyOptional({
    description: 'Only accepted and active stations',
    example: true,
    default: true,
  })
  @IsOptional()
  @IsBoolean()
  @Type(() => Boolean)
  accepted?: boolean;
}

export class GetStationAvailabilityDto {
  @ApiProperty({
    description: 'Jalali date in format YYYY/MM/DD (e.g., 1404/08/18)',
    example: '1404/08/18',
  })
  @IsString()
  @IsNotEmpty()
  date: string;

  @ApiProperty({
    description: 'Station ID',
    example: 1,
  })
  @IsNumber()
  @IsNotEmpty()
  @Type(() => Number)
  stationId: number;
}

export class TimeSlotResponseDto {
  @ApiProperty({
    description: 'Start time of the slot',
    example: '2024-12-01T09:00:00.000Z',
  })
  startTime: Date;

  @ApiProperty({
    description: 'End time of the slot',
    example: '2024-12-01T09:30:00.000Z',
  })
  endTime: Date;

  @ApiProperty({
    description: 'Time label (HH:MM - HH:MM)',
    example: '09:00 - 09:30',
  })
  label: string;

  @ApiProperty({
    description: 'Is this slot reserved',
    example: false,
  })
  isReserved: boolean;

  @ApiProperty({
    description: 'Is this slot available (not reserved and not in the past)',
    example: true,
  })
  isAvailable: boolean;
}

export class StationAvailabilityResponseDto {
  @ApiProperty({
    description: 'Station information',
  })
  station: {
    id: number;
    title: string;
    consoleId: number;
    capacity: number;
    status: boolean;
    isActive: boolean;
    isAccepted: boolean;
    console: {
      id: number;
      name: string;
      manufacturer: string | null;
      category: string;
    };
    pricings: {
      playerCount: number;
      price: number;
    }[];
    stationGames: {
      game: {
        id: number;
        title: string;
        coverImage: string | null;
      };
    }[];
  };

  @ApiProperty({
    description: 'Organization working hours for the requested date',
  })
  workingHours: {
    dayOfWeek: number;
    isClosed: boolean;
    is24Hours: boolean;
    startTime: string | null;
    endTime: string | null;
  };

  @ApiProperty({
    description: 'Available time slots for the requested date',
    type: [TimeSlotResponseDto],
  })
  timeSlots: TimeSlotResponseDto[];
}
